name: Deploy to Firebase Hosting on PR
'on': pull_request_target
jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set branch name
        run: echo "BRANCH_NAME=${{ github.head_ref }}" >> $GITHUB_ENV
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_ASTAR_TOKEN_API }}'
          projectId: astar-token-api
          onlyBranches: ${{ env.BRANCH_NAME }}
